const py = (body: string) => `import sys\n${body}\n`;

/** Original problems. Statements are written for this project; they are not copied from another site. */
export const MORE = [
  {
    title: 'Digit sum',
    statement: 'Read a non-negative integer and print the sum of its decimal digits.',
    samples: 'Input\n205\nOutput\n7',
    editorial: 'Repeatedly take the number modulo 10 and divide by 10. Zero sums to zero.',
    tags: ['math', 'implementation'],
    contest: false,
    pool: 'practice',
    difficulty: 'easy',
    reference: py('n=int(sys.stdin.read())\nprint(sum(int(ch) for ch in str(n)))'),
    wrong: py('n=int(sys.stdin.read())\nprint(n)'),
    tests: [
      { input: '205\n', output: '7\n', hidden: false },
      { input: '0\n', output: '0\n', hidden: true },
      { input: '999\n', output: '27\n', hidden: true },
    ],
  },
  {
    title: 'Absolute difference',
    statement: 'Read two integers and print the absolute difference between them.',
    samples: 'Input\n3 8\nOutput\n5',
    editorial: 'Subtract and drop the sign. Equal numbers give zero.',
    tags: ['math'],
    contest: false,
    pool: 'practice',
    difficulty: 'easy',
    reference: py('a,b=map(int,sys.stdin.read().split())\nprint(abs(a-b))'),
    wrong: py('a,b=map(int,sys.stdin.read().split())\nprint(a-b)'),
    tests: [
      { input: '3 8\n', output: '5\n', hidden: false },
      { input: '8 3\n', output: '5\n', hidden: true },
      { input: '-2 2\n', output: '4\n', hidden: true },
    ],
  },
  {
    title: 'Palindrome word',
    statement: 'Read one word of lowercase letters and print yes if it reads the same forwards and backwards, otherwise no.',
    samples: 'Input\nlevel\nOutput\nyes',
    editorial: 'Compare the string with its reverse. A single letter is a palindrome.',
    tags: ['strings'],
    contest: false,
    pool: 'archive',
    difficulty: 'easy',
    reference: py('s=sys.stdin.read().strip()\nprint("yes" if s==s[::-1] else "no")'),
    wrong: py('print("yes")'),
    tests: [
      { input: 'level\n', output: 'yes\n', hidden: false },
      { input: 'ab\n', output: 'no\n', hidden: true },
      { input: 'a\n', output: 'yes\n', hidden: true },
    ],
  },
  {
    title: 'Minimum of a list',
    statement: 'The first integer n is the length. The next n integers follow. Print the smallest of them.',
    samples: 'Input\n3\n4 1 9\nOutput\n1',
    editorial: 'Track the smallest value while scanning. Do not include the length itself.',
    tags: ['implementation'],
    contest: false,
    pool: 'archive',
    difficulty: 'easy',
    reference: py('d=list(map(int,sys.stdin.read().split()))\nprint(min(d[1:1+d[0]]))'),
    wrong: py('d=list(map(int,sys.stdin.read().split()))\nprint(d[0])'),
    tests: [
      { input: '3\n4 1 9\n', output: '1\n', hidden: false },
      { input: '1\n-7\n', output: '-7\n', hidden: true },
      { input: '4\n5 5 5 5\n', output: '5\n', hidden: true },
    ],
  },
  {
    title: 'Greatest common divisor',
    statement: 'Read two positive integers and print their greatest common divisor.',
    samples: 'Input\n12 18\nOutput\n6',
    editorial: 'Euclid’s algorithm: replace the larger by the remainder until one of them is zero. The other is the answer.',
    tags: ['math', 'number-theory'],
    contest: false,
    pool: 'practice',
    difficulty: 'easy',
    reference: py('import math\na,b=map(int,sys.stdin.read().split())\nprint(math.gcd(a,b))'),
    wrong: py('a,b=map(int,sys.stdin.read().split())\nprint(a)'),
    tests: [
      { input: '12 18\n', output: '6\n', hidden: false },
      { input: '7 1\n', output: '1\n', hidden: true },
      { input: '13 13\n', output: '13\n', hidden: true },
    ],
  },
  {
    title: 'Prime check',
    statement: 'Read an integer n (2 ≤ n ≤ 10000) and print yes if it is prime, otherwise no.',
    samples: 'Input\n7\nOutput\nyes',
    editorial: 'A prime has no divisor from 2 up to its square root. 2 is prime; 4 is not.',
    tags: ['math', 'number-theory'],
    contest: false,
    pool: 'practice',
    difficulty: 'easy',
    reference: py('n=int(sys.stdin.read())\nok=n>1 and all(n%d for d in range(2,int(n**0.5)+1))\nprint("yes" if ok else "no")'),
    wrong: py('n=int(sys.stdin.read())\nprint("yes" if n%2 else "no")'),
    tests: [
      { input: '7\n', output: 'yes\n', hidden: false },
      { input: '4\n', output: 'no\n', hidden: true },
      { input: '2\n', output: 'yes\n', hidden: true },
      { input: '9\n', output: 'no\n', hidden: true },
    ],
  },
  {
    title: 'Fibonacci number',
    statement: 'Read n (0 ≤ n ≤ 40). Print the n-th Fibonacci number, with F(0) = 0 and F(1) = 1.',
    samples: 'Input\n6\nOutput\n8',
    editorial: 'Keep the last two values and step forward n times. Recursion without a cache is unnecessary at this limit.',
    tags: ['dp', 'math'],
    contest: false,
    pool: 'archive',
    difficulty: 'easy',
    reference: py('n=int(sys.stdin.read())\na,b=0,1\nfor _ in range(n):\n a,b=b,a+b\nprint(a)'),
    wrong: py('n=int(sys.stdin.read())\nprint(n)'),
    tests: [
      { input: '6\n', output: '8\n', hidden: false },
      { input: '0\n', output: '0\n', hidden: true },
      { input: '1\n', output: '1\n', hidden: true },
      { input: '10\n', output: '55\n', hidden: true },
    ],
  },
  {
    title: 'Count distinct',
    statement: 'The first integer n is the length. The next n integers follow. Print how many distinct values appear.',
    samples: 'Input\n5\n1 2 1 2 3\nOutput\n3',
    editorial: 'Put the values in a set and print its size. Order does not matter.',
    tags: ['implementation'],
    contest: false,
    pool: 'practice',
    difficulty: 'easy',
    reference: py('d=list(map(int,sys.stdin.read().split()))\nprint(len(set(d[1:1+d[0]])))'),
    wrong: py('d=list(map(int,sys.stdin.read().split()))\nprint(d[0])'),
    tests: [
      { input: '5\n1 2 1 2 3\n', output: '3\n', hidden: false },
      { input: '1\n4\n', output: '1\n', hidden: true },
      { input: '3\n8 8 8\n', output: '1\n', hidden: true },
    ],
  },
  {
    title: 'Longest run',
    statement: 'Read one string of lowercase letters and print the length of the longest run of the same character.',
    samples: 'Input\naabccc\nOutput\n3',
    editorial: 'Walk once, counting the current run and remembering the longest. An empty string cannot occur; a single character is 1.',
    tags: ['strings'],
    contest: false,
    pool: 'archive',
    difficulty: 'easy',
    reference: py('s=sys.stdin.read().strip()\nbest=run=1\nfor i in range(1,len(s)):\n run=run+1 if s[i]==s[i-1] else 1\n best=max(best,run)\nprint(best)'),
    wrong: py('s=sys.stdin.read().strip()\nprint(len(s))'),
    tests: [
      { input: 'aabccc\n', output: '3\n', hidden: false },
      { input: 'abc\n', output: '1\n', hidden: true },
      { input: 'zzzz\n', output: '4\n', hidden: true },
    ],
  },
  {
    title: 'Balanced brackets',
    statement: 'Read one string of parentheses. Print yes if every opening bracket has a matching close in order, otherwise no.',
    samples: 'Input\n(())\nOutput\nyes',
    editorial: 'A counter works: increment on “(”, decrement on “)”, and reject a negative count or a leftover count.',
    tags: ['strings', 'stacks'],
    contest: false,
    pool: 'practice',
    difficulty: 'medium',
    reference: py('s=sys.stdin.read().strip()\nd=0\nok=True\nfor ch in s:\n d+=1 if ch=="(" else -1\n if d<0: ok=False\nprint("yes" if ok and d==0 else "no")'),
    wrong: py('s=sys.stdin.read().strip()\nprint("yes" if s.count("(")==s.count(")") else "no")'),
    tests: [
      { input: '(())\n', output: 'yes\n', hidden: false },
      { input: '())(\n', output: 'no\n', hidden: true },
      { input: '(\n', output: 'no\n', hidden: true },
      { input: '\n', output: 'yes\n', hidden: true },
    ],
  },
  {
    title: 'Pair with a given sum',
    statement: 'The first line has n and target. The second line has n integers, already sorted ascending. Print yes if two different positions sum to target, otherwise no.',
    samples: 'Input\n4 9\n1 3 6 8\nOutput\nyes',
    editorial: 'Two pointers from the ends. Move the left pointer when the sum is too small and the right pointer when it is too large.',
    tags: ['two-pointers', 'sorting'],
    contest: false,
    pool: 'archive',
    difficulty: 'medium',
    reference: py('d=list(map(int,sys.stdin.read().split()))\nn,t=d[0],d[1]\na=d[2:2+n]\ni,j=0,n-1\nok=False\nwhile i<j:\n s=a[i]+a[j]\n if s==t: ok=True; break\n if s<t: i+=1\n else: j-=1\nprint("yes" if ok else "no")'),
    wrong: py('print("no")'),
    tests: [
      { input: '4 9\n1 3 6 8\n', output: 'yes\n', hidden: false },
      { input: '3 100\n1 2 3\n', output: 'no\n', hidden: true },
      { input: '2 5\n2 3\n', output: 'yes\n', hidden: true },
    ],
  },
  {
    title: 'Range sum',
    statement: 'The first line has n and q. The second line has n integers. Each of the next q lines has l and r, 1-based inclusive indexes. Print q lines, the sum of each range.',
    samples: 'Input\n4 2\n1 2 3 4\n1 3\n2 4\nOutput\n6\n9',
    editorial: 'Build a prefix array once. A range sum is prefix[r] − prefix[l−1].',
    tags: ['prefix-sums'],
    contest: false,
    pool: 'practice',
    difficulty: 'medium',
    reference: py('d=sys.stdin.read().split()\nit=iter(d)\nn,q=int(next(it)),int(next(it))\na=[int(next(it)) for _ in range(n)]\np=[0]\nfor x in a: p.append(p[-1]+x)\nout=[]\nfor _ in range(q):\n l,r=int(next(it)),int(next(it))\n out.append(str(p[r]-p[l-1]))\nprint("\\n".join(out))'),
    wrong: py('print(0)'),
    tests: [
      { input: '4 2\n1 2 3 4\n1 3\n2 4\n', output: '6\n9\n', hidden: false },
      { input: '1 1\n5\n1 1\n', output: '5\n', hidden: true },
      { input: '3 1\n-1 0 4\n1 3\n', output: '3\n', hidden: true },
    ],
  },
  {
    title: 'Climbing stairs',
    statement: 'Read n (1 ≤ n ≤ 40). You can climb 1 or 2 stairs at a time. Print how many distinct ways there are to climb exactly n stairs.',
    samples: 'Input\n3\nOutput\n3',
    editorial: 'The answer is the Fibonacci recurrence ways(n) = ways(n−1) + ways(n−2), with ways(1) = 1 and ways(2) = 2.',
    tags: ['dp'],
    contest: false,
    pool: 'archive',
    difficulty: 'medium',
    reference: py('n=int(sys.stdin.read())\na,b=1,1\nfor _ in range(n):\n a,b=b,a+b\nprint(a)'),
    wrong: py('n=int(sys.stdin.read())\nprint(n)'),
    tests: [
      { input: '3\n', output: '3\n', hidden: false },
      { input: '1\n', output: '1\n', hidden: true },
      { input: '4\n', output: '5\n', hidden: true },
    ],
  },
  {
    title: 'Rotate left',
    statement: 'The first line has n and k. The second line has n integers. Print them rotated left by k positions. k may be larger than n.',
    samples: 'Input\n5 2\n1 2 3 4 5\nOutput\n3 4 5 1 2',
    editorial: 'Reduce k modulo n, then print a[k:] + a[:k]. A multiple of n changes nothing.',
    tags: ['arrays'],
    contest: false,
    pool: 'practice',
    difficulty: 'medium',
    reference: py('d=list(map(int,sys.stdin.read().split()))\nn,k=d[0],d[1]%d[0]\na=d[2:2+n]\na=a[k:]+a[:k]\nprint(*a)'),
    wrong: py('d=list(map(int,sys.stdin.read().split()))\nprint(*d[2:])'),
    tests: [
      { input: '5 2\n1 2 3 4 5\n', output: '3 4 5 1 2\n', hidden: false },
      { input: '3 3\n1 2 3\n', output: '1 2 3\n', hidden: true },
      { input: '3 4\n9 8 7\n', output: '8 7 9\n', hidden: true },
    ],
  },
  {
    title: 'Maximum subarray',
    statement: 'The first integer n is the length. The next n integers follow, and at least one is positive. Print the largest sum of a contiguous subarray.',
    samples: 'Input\n5\n-2 1 -3 4 -1\nOutput\n4',
    editorial: 'Kadane’s scan: extend the current sum, or start over when the current sum would go negative.',
    tags: ['dp', 'arrays'],
    contest: false,
    pool: 'archive',
    difficulty: 'medium',
    reference: py('d=list(map(int,sys.stdin.read().split()))\na=d[1:1+d[0]]\nbest=cur=a[0]\nfor x in a[1:]:\n cur=max(x,cur+x)\n best=max(best,cur)\nprint(best)'),
    wrong: py('d=list(map(int,sys.stdin.read().split()))\nprint(sum(d[1:]))'),
    tests: [
      { input: '5\n-2 1 -3 4 -1\n', output: '4\n', hidden: false },
      { input: '1\n5\n', output: '5\n', hidden: true },
      { input: '4\n1 -2 3 1\n', output: '4\n', hidden: true },
    ],
  },
  {
    title: 'Bounded knapsack',
    statement: 'The first line has n and capacity W (1 ≤ n ≤ 20, 1 ≤ W ≤ 200). Each of the next n lines has a weight and a value. Each item may be taken at most once. Print the largest total value that fits in W.',
    samples: 'Input\n3 5\n2 3\n3 4\n4 5\nOutput\n7',
    editorial: 'With n ≤ 20 a bit mask is enough: try every subset, keep those whose weight fits, and remember the best value.',
    tags: ['dp', 'knapsack'],
    contest: false,
    pool: 'archive',
    difficulty: 'hard',
    reference: py('lines=sys.stdin.read().splitlines()\nn,W=map(int,lines[0].split())\nitems=[tuple(map(int,line.split())) for line in lines[1:1+n]]\nbest=0\nfor mask in range(1<<n):\n w=v=0\n for i in range(n):\n  if mask>>i&1:\n   w+=items[i][0]; v+=items[i][1]\n if w<=W: best=max(best,v)\nprint(best)'),
    wrong: py('print(0)'),
    tests: [
      { input: '3 5\n2 3\n3 4\n4 5\n', output: '7\n', hidden: false },
      { input: '1 1\n2 9\n', output: '0\n', hidden: true },
      { input: '2 10\n4 5\n6 7\n', output: '12\n', hidden: true },
    ],
  },
  {
    title: 'Shortest path in a line',
    statement: 'Read n and m, then m edges “u v” on an undirected graph with nodes 1..n. Print the fewest edges from 1 to n, or -1 if n cannot be reached.',
    samples: 'Input\n4 3\n1 2\n2 3\n3 4\nOutput\n3',
    editorial: 'Breadth-first search from 1. The first time n is reached, the distance is minimal.',
    tags: ['graphs', 'bfs'],
    contest: false,
    pool: 'practice',
    difficulty: 'hard',
    reference: py('from collections import deque\nd=sys.stdin.read().split()\nit=iter(d)\nn,m=int(next(it)),int(next(it))\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n u,v=int(next(it)),int(next(it))\n g[u].append(v); g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\nq=deque([1])\nwhile q:\n u=q.popleft()\n for v in g[u]:\n  if dist[v]<0:\n   dist[v]=dist[u]+1\n   q.append(v)\nprint(dist[n])'),
    wrong: py('print(0)'),
    tests: [
      { input: '4 3\n1 2\n2 3\n3 4\n', output: '3\n', hidden: false },
      { input: '2 0\n', output: '-1\n', hidden: true },
      { input: '3 2\n1 2\n1 3\n', output: '1\n', hidden: true },
    ],
  },
  {
    title: 'Partial double',
    statement: 'Read one integer and print twice that integer.\n\nInput\nA single integer n.\n\nOutput\nPrint 2n.\n\nNote\nThe sample group is worth 30 points. The full group is worth 70. Solving only the sample still scores.',
    samples: 'Input\n4\nOutput\n8',
    editorial: 'Multiply by two. A solution that only handles non-negative input still passes the sample group.',
    tags: ['math', 'subtasks'],
    contest: false,
    pool: 'practice',
    difficulty: 'medium',
    subtasks: [{ name: 'sample', points: 30 }, { name: 'full', points: 70 }],
    reference: py('n=int(sys.stdin.read())\nprint(n*2)'),
    wrong: py('n=int(sys.stdin.read())\nprint(n*2 if n>=0 else n)'),
    tests: [
      { input: '4\n', output: '8\n', hidden: false, group: 'sample' },
      { input: '0\n', output: '0\n', hidden: true, group: 'sample' },
      { input: '-3\n', output: '-6\n', hidden: true, group: 'full' },
      { input: '100\n', output: '200\n', hidden: true, group: 'full' },
    ],
  },
];
